
name: test pipeline
spec:
  sequential:
    - name: dl
      processor:
        type: http
        version: 1.0
        configuration:
          url: http://google.com
      children:
        sequential:
          - name: decompress
            processor:
              type: extract
              version: 1.0
          - name: t
            processor:
              type: test
              version: 1.0
        parallel:
          - name: test
            processor:
              type: test
              version: 1.0
          - name: test2
            processor:
              type: test
              version: 1.0