name: test pipeline
# this data is passed to the first pipeline
data:
  url: https://download.bls.gov/pub/time.series/la/
  files:
    - la.seasonal
    - la.period
spec:
  sequential:
    - name: dl
      processor:
        name: http
        version: 1.0
        configuration:
          url: http://google.com
      children:
        sequential:
          - name: decompress
            processor:
              name: extract
              version: 1.0
          - name: t
            processor:
              name: test
              version: 1.0
        parallel:
          - name: test
            processor:
              name: test
              version: 1.0
          - name: test2
            processor:
              name: test
              version: 1.0