name: download pipeline
# 
data:
  urls:
    - https://download.bls.gov/pub/time.series/la/la.seasonal
    - https://download.bls.gov/pub/time.series/la/la.period
spec:
  sequential:
    - name: dl
      processor:
        id: get
        version: 1.0 # version matching isn't implemented yet
    - name: list output
      description: should list the output of the previous step
      processor:
        id: ls