# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    environment: # TODO: add matrix builds for mac, windows, etc
      - GOOS: "linux"
      - GOARCH: "amd64"
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/tim15/wiz
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    # Builds wiz for each architecture
    docker:
      # specify the version
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/tim15/wiz
    steps:
      - checkout

      - run: cd build && ./matrix.sh && ls

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: build
          # Must be relative path from root
          paths:
            - out
  build_docker:
    # Builds and pushes docker images for each arch built.
    # parallelism: 2
    docker:
      # specify the version
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/tim15/wiz
    steps:
      - checkout
      - attach_workspace:
        # Must be absolute path or relative path from working_directory
        at: build/out
      # Docker build + push
      - setup_remote_docker:
          version: 17.06.0-ce
      - run: export BUILD_TYPE="docker"
      - run: cd build && ./matrix.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # TODO: build docker
      # - build_docker:
      #     requires: build
      - test
