basePath: /
definitions:
  processors.Configuration:
    properties:
      ExecutorConfig:
        $ref: '#/definitions/processors.ExecutorConfig'
        type: object
      ExpectedData:
        $ref: '#/definitions/processors.ExpectedData'
        description: Embeded structs have a weird JSON serialization issue
        type: object
      Processor:
        type: object
    type: object
  processors.Data:
    properties:
      AssociatedChunkID:
        description: |-
          this is a reference to the opposing data chunk. If it is an input chunk this references the output.
          If it is an output chunk it references the input chunk
        type: string
      ChunkID:
        type: string
      FilesystemReference:
        $ref: '#/definitions/processors.FilesystemReference'
        type: object
      Format:
        type: integer
      RawData:
        type: object
      State:
        type: integer
      Type:
        type: integer
    type: object
  processors.DataSpec:
    properties:
      In:
        items:
          $ref: '#/definitions/processors.Data'
        type: array
      Out:
        items:
          $ref: '#/definitions/processors.Data'
        type: array
    type: object
  processors.DownstreamDataLocation:
    properties:
      Hostname:
        type: string
      ProcID:
        type: string
      RunID:
        type: string
    type: object
  processors.ExecutorConfig:
    properties:
      DownstreamLocations:
        description: |-
          TODO: make API URL templating agnostic, refactor into server package
          e.g. Server.GetProc(procID, runID) will return /processors/procID/runs/runID
          this could be used both for generating endpoints and here, for passing outputs downstream
        items:
          $ref: '#/definitions/processors.DownstreamDataLocation'
        type: array
      MaxWorkers:
        type: integer
      SendDownstream:
        type: boolean
    type: object
  processors.ExpectedData:
    properties:
      NumChunks:
        description: a counter value
        type: integer
    type: object
  processors.FilesystemReference:
    properties:
      Driver:
        description: the filesystem driver (e.g. NFS, local, ZFS, etc)
        type: string
      Location:
        description: the actual file path location
        type: string
    type: object
  processors.Processor:
    properties:
      Name:
        description: ID is the human readable name
        type: string
      ProcID:
        description: ProcID is the uniquely identifiable Processor ID
        type: string
      Version:
        type: string
    type: object
  processors.Processors:
    items:
      $ref: '#/definitions/processors.Processor'
    type: array
  processors.Run:
    properties:
      Configuration:
        $ref: '#/definitions/processors.Configuration'
        type: object
      CurrentState:
        description: |-
          Note: Embedding structs will automatically promote the child struct's functions,
          and since our State type is an enum that overrides the default Marshal and Unmarshal functions,
          it overwrites it for the parent type as well.
          Remember, the CurrentState must be updated from the RunProcessor state to be fresh. TODO: think about these guarantees
        type: integer
      RunID:
        type: string
    type: object
  processors.Runs:
    items:
      $ref: '#/definitions/processors.Run'
    type: array
  server.Empty:
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the HTTP + JSON + REST version of the Wiz Processor API.
  license:
    name: Apache 2.0
  title: Wiz Processor API
  version: "1.0"
paths:
  /processors:
    get:
      consumes:
      - application/json
      operationId: GetAllProcessors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/processors.Processors'
      summary: Retrieves all processors
  /processors/{id}:
    get:
      consumes:
      - application/json
      operationId: GetProcessor
      parameters:
      - description: Processor ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/processors.Processor'
      summary: Retrieves a single processor
  /processors/{procID}/runs:
    get:
      consumes:
      - application/json
      operationId: GetAllRuns
      parameters:
      - description: Processor ID
        in: path
        name: procID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/processors.Runs'
      summary: Retrieves all runs
  /processors/{procID}/runs/{runID}:
    get:
      consumes:
      - application/json
      operationId: GetRun
      parameters:
      - description: Processor ID
        in: path
        name: procID
        required: true
        type: string
      - description: Run ID
        in: path
        name: runID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/processors.Run'
      summary: Retrieves a single run
  /processors/{procID}/runs/{runID}/config:
    get:
      consumes:
      - application/json
      operationId: GetConfig
      parameters:
      - description: Processor ID
        in: path
        name: procID
        required: true
        type: string
      - description: Run ID
        in: path
        name: runID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/processors.Configuration'
      summary: Retrieves a single run's configuration
    post:
      consumes:
      - application/json
      operationId: Configure
      parameters:
      - description: Processor ID
        in: path
        name: procID
        required: true
        type: string
      - description: Run ID
        in: path
        name: runID
        required: true
        type: string
      - description: Configuration to set
        in: body
        name: configuration
        required: true
        schema:
          $ref: '#/definitions/processors.Configuration'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Sets a single run's configuration
  /processors/{procID}/runs/{runID}/data:
    get:
      consumes:
      - application/json
      operationId: GetData
      parameters:
      - description: Processor ID
        in: path
        name: procID
        required: true
        type: string
      - description: Run ID
        in: path
        name: runID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/processors.DataSpec'
      summary: Gets data to the run
    post:
      consumes:
      - application/json
      operationId: AddData
      parameters:
      - description: Processor ID
        in: path
        name: procID
        required: true
        type: string
      - description: Run ID
        in: path
        name: runID
        required: true
        type: string
      - description: Data to add
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/processors.Data'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Adds data from the run
swagger: "2.0"
